Adds new component: Form.Autocomplete
Automattic/vip-design-system pull request #127
Opened 2022-10-27 14:14 UTC by luiztiago

## Description

Adding the `Form/Autocomplete` new component 🥳 . 

We're using the accessible autocomplete from alphagov as a base, and doing the styling update to have it similar to the VIP design system. A few usage examples are available on [component website](https://alphagov.github.io/accessible-autocomplete/examples/)

### VIP Form/Autocomplete component

<img width="453" alt="image" src="https://user-images.githubusercontent.com/199867/198309289-3ce7e19a-2b28-4b16-99fd-08990db8bb6c.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/199867/198309523-6b902502-05a9-4532-a1e1-05e88eaf1d4b.png">

## Checklist

- [ ] This PR has good automated test coverage
- [x] The storybook for the component has been updated

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Pull down PR.
1. `npm run dev`.
1. Open Storybook.
1. Check how the Autocomplete behaves similarly to the component, but with accessibility. You can use a keyboard, and navigate between options, etc.

2022-10-31 11:12 UTC, rianrietveld approved these changes
@djalmaaraujo 
As good as it gets ...
Very verbose, but it works.
Only yo be used in the case of many options.

2022-10-31 13:36 UTC, djalmaaraujo requested changes
This is amazing @luiztiago!

Thanks a lot for this component; this will be a fantastic change and impact on the VIP apps.

Left some minor suggestions.

Ps: Can you add a basic test at least with the rendered + axe no violations?

2022-10-31 13:36 UTC, djalmaaraujo commented on src/system/NewForm/FormAutocomplete.js
> +	borderWidth: '0px',
I think 0 is enough.

2022-10-31 13:36 UTC, djalmaaraujo commented on src/system/NewForm/FormAutocomplete.js
> +			id = 'autocomplete',
Can we make `vip-autocomplete`?

2022-10-31 13:36 UTC, djalmaaraujo commented on src/system/NewForm/FormAutocomplete.js
> +			document.querySelector( '.autocomplete__input' ).setAttribute( 'aria-activedescendant', '' );
Try `global.document`

2022-10-31 13:36 UTC, djalmaaraujo commented on src/system/NewForm/FormAutocomplete.js
> +		}, [] );
is this not complaining about putting document here? if yes, try `global`

2022-11-03 19:41 UTC, djalmaaraujo approved these changes

2022-11-03 19:45 UTC, merged