[WIP] Update/valet theme
Automattic/vip-design-system pull request #138
Opened 2022-11-16 20:02 UTC by djalmaaraujo

## Description

This is a work in progress. I am adapting the current styles to the most up-to-date FIGMA files from the valet theme.

TBD

2022-12-22 01:36 UTC, luiztiago reviewed
Great job. The storybook and UI are much better now.
I suggested only two minor updates.

2022-12-22 01:36 UTC, luiztiago commented on src/system/Badge/Badge.stories.jsx
> +const BBadge = props => <Badge { ...props } sx={ { m: 2 } } />;
Maybe we can use `const Template` here, such as is used on other files.

2022-12-22 01:36 UTC, luiztiago commented on src/system/Form/Radio.js
> +import { getColor } from '../theme/getColor';
Can we remote this line?

2022-12-22 06:54 UTC, pandah3 reviewed
What's the best way to test this? I'm not sure where to even start 😅

Should we go through all the components in the [Netlify previews](https://deploy-preview-138--vip-design-system-components.netlify.app/) and compare the colors with the expected colors from the [Valet tokens](https://github.com/Automattic/vip-design-system/blob/trunk/tokens/valet-core.json)? This obviously isn't practical so I'm missing something here lol..

2022-12-22 15:32 UTC, djalmaaraujo commented
> What's the best way to test this? I'm not sure where to even start 😅
> 
> Should we go through all the components in the [Netlify previews](https://deploy-preview-138--vip-design-system-components.netlify.app/) and compare the colors with the expected colors from the [Valet tokens](https://github.com/Automattic/vip-design-system/blob/trunk/tokens/valet-core.json)? This obviously isn't practical so I'm missing something here lol..

Thanks for the question. You can review all the components in the Netlify preview and make sure they work. We only changed colors; there's no new functionality. 

Some things were removed or deprecated too, but that's minimal, no effect.

I will add a proper way to test in the instructions, but in general, you can also grab the branch into the VIP Dashboard and to some navigation there.

2022-12-22 21:05 UTC, pandah3 requested changes
Thank you for the updated testing instructions!

Testing with Netlify, a good chunk of the components have accessibility violations in Dark Mode 😢 . These are the ones I found with the violations:

- Accordion
  - Default
- Button
  - Default
  - Link
  - With on click
- Dropdown
  - Default
  - Complex options
  - (With Dialog is good, no violations)
- Option row
  - Default
- Table
  - Default
- Tabs
  - Default
  - (Set active tab is good, no violations)
- Text
  - Default
- Wizard
  - Default
  - (Custom title is good, no violations)
- Autocomplete
  - Default
  - Inline
  - (Others are good)
- Checkbox
  - Default
- Input
  - Default
- Label
  - Required
  - (Default is good, no violations)
- Radio
  - Default
- Select
  - Default
  - With Group
  - Is Inline
  - With Option Label and Value
  - With On Change
- Textarea
  - Default

2022-12-22 21:13 UTC, djalmaaraujo commented
> Thank you for the updated testing instructions!
> 
> Testing with Netlify, a good chunk of the components have accessibility violations in Dark Mode 😢 . These are the ones I found with the violations:
> 
> * Accordion
>   
>   * Default
> * Button
>   
>   * Default
>   * Link
>   * With on click
> * Dropdown
>   
>   * Default
>   * Complex options
>   * (With Dialog is good, no violations)
> * Option row
>   
>   * Default
> * Table
>   
>   * Default
> * Tabs
>   
>   * Default
>   * (Set active tab is good, no violations)
> * Text
>   
>   * Default
> * Wizard
>   
>   * Default
>   * (Custom title is good, no violations)
> * Autocomplete
>   
>   * Default
>   * Inline
>   * (Others are good)
> * Checkbox
>   
>   * Default
> * Input
>   
>   * Default
> * Label
>   
>   * Required
>   * (Default is good, no violations)
> * Radio
>   
>   * Default
> * Select
>   
>   * Default
>   * With Group
>   * Is Inline
>   * With Option Label and Value
>   * With On Change
> * Textarea
>   
>   * Default

Thanks for the reply, but dark mode is not included in the scope of these changes.

2022-12-23 01:42 UTC, pandah3 commented
Noting that this will break Dark Mode even more, so we will be disabling Dark Mode in a separate PR.
https://a8c.slack.com/archives/CKUJZT08Y/p1671744028394699

2022-12-23 02:08 UTC, pandah3 requested changes
Thank you for working on this enormous effort 🎉 
I tested this PR with the [draft Dashboard PR](https://github.com/Automattic/vip-dashboard/pull/2530) using the axe DevTools extension.

Went through all the panels and flows I could in the VIP Dashboard and found some violations of `Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds`:

1. [Database Backups](http://localhost:3000/apps/4018/production/data/database/backups) - [Axe issue](https://axe.deque.com/issues/fe070724-61fe-4658-9108-6b0aba7e791b
)
```
Element has insufficient color contrast of 3.89 (foreground color: #e74135, background color: #fbfbfb, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
```

<img width="809" alt="Screen Shot 2022-12-22 at 5 48 25 PM" src="https://user-images.githubusercontent.com/29221840/209254749-e01ce455-726b-4be7-8bf8-c0a0d32d02d6.png">

2. Media Backups - [Axe issue](https://axe.deque.com/issues/a6d9b72e-c6c4-4d68-94e7-7590e83c6ead)
```
Element has insufficient color contrast of 3.94 (foreground color: #808080, background color: #ffffff, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
```
<img width="556" alt="Screen Shot 2022-12-22 at 5 51 56 PM" src="https://user-images.githubusercontent.com/29221840/209255084-a020c8ef-b0ab-4446-939d-c1b8539f2789.png">

3. Deployments - [Axe issue](https://axe.deque.com/issues/fdd904c2-1937-4ab0-820b-5b490904093e)
<img width="549" alt="Screen Shot 2022-12-22 at 5 54 00 PM" src="https://user-images.githubusercontent.com/29221840/209255289-1b092365-1a0a-411d-8bda-7180e21eda16.png">

4. Certs - [Axe issue](https://axe.deque.com/issues/71f2c88a-4132-45e6-a73a-2b528785ede9)
```
Element has insufficient color contrast of 2.58 (foreground color: #fbfbfb, background color: #d29137, font size: 10.0pt (13.3333px), font weight: normal). Expected contrast ratio of 4.5:1
```
<img width="806" alt="Screen Shot 2022-12-22 at 5 55 43 PM" src="https://user-images.githubusercontent.com/29221840/209255681-ba09cce1-13d9-4568-83be-d11e981b1233.png">

5. [Audit log ](http://localhost:3000/apps/5264/production/audit-log?from=2022-12-20T15%3A10%3A37.000Z&eventId=g%3A6617872)- [Axe issue](https://axe.deque.com/issues/e7b864ab-3f43-4222-bf8c-6458308c759d)

<img width="549" alt="Screen Shot 2022-12-22 at 5 58 57 PM" src="https://user-images.githubusercontent.com/29221840/209255826-db2875fb-acf3-44c6-8194-fe3720cb0bab.png">

7. Usage - Axe issues [1](https://axe.deque.com/issues/537378c3-1dc0-4077-8c49-2cd9081a1ab9), [2](https://axe.deque.com/issues/d1d3057a-568c-471d-8ef3-46300d8f9789), [3](https://axe.deque.com/issues/03c6bb7b-7384-4085-97da-dc3b9e91949f)

<img width="379" alt="Screen Shot 2022-12-22 at 6 06 23 PM copy" src="https://user-images.githubusercontent.com/29221840/209256766-fc23c467-2b44-49b2-b1e6-0bdf94d412e5.png">

2022-12-26 17:54 UTC, djalmaaraujo commented
> Thank you for working on this enormous effort 🎉 I tested this PR with the [draft Dashboard PR](https://github.com/Automattic/vip-dashboard/pull/2530) using the axe DevTools extension.
> 
> Went through all the panels and flows I could in the VIP Dashboard and found some violations of `Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds`:
> 
> 1. [Database Backups](http://localhost:3000/apps/4018/production/data/database/backups) - [Axe issue](https://axe.deque.com/issues/fe070724-61fe-4658-9108-6b0aba7e791b)
> 
> ```
> Element has insufficient color contrast of 3.89 (foreground color: #e74135, background color: #fbfbfb, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
> ```
> 
> <img alt="Screen Shot 2022-12-22 at 5 48 25 PM" width="809" src="https://user-images.githubusercontent.com/29221840/209254749-e01ce455-726b-4be7-8bf8-c0a0d32d02d6.png">
> 
> 2. Media Backups - [Axe issue](https://axe.deque.com/issues/a6d9b72e-c6c4-4d68-94e7-7590e83c6ead)
> 
> ```
> Element has insufficient color contrast of 3.94 (foreground color: #808080, background color: #ffffff, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1
> ```
> 
> <img alt="Screen Shot 2022-12-22 at 5 51 56 PM" width="556" src="https://user-images.githubusercontent.com/29221840/209255084-a020c8ef-b0ab-4446-939d-c1b8539f2789.png">
> 
> 3. Deployments - [Axe issue](https://axe.deque.com/issues/fdd904c2-1937-4ab0-820b-5b490904093e)
> 
> <img alt="Screen Shot 2022-12-22 at 5 54 00 PM" width="549" src="https://user-images.githubusercontent.com/29221840/209255289-1b092365-1a0a-411d-8bda-7180e21eda16.png">
> 
> 4. Certs - [Axe issue](https://axe.deque.com/issues/71f2c88a-4132-45e6-a73a-2b528785ede9)
> 
> ```
> Element has insufficient color contrast of 2.58 (foreground color: #fbfbfb, background color: #d29137, font size: 10.0pt (13.3333px), font weight: normal). Expected contrast ratio of 4.5:1
> ```
> 
> <img alt="Screen Shot 2022-12-22 at 5 55 43 PM" width="806" src="https://user-images.githubusercontent.com/29221840/209255681-ba09cce1-13d9-4568-83be-d11e981b1233.png">
> 
> 5. [Audit log ](http://localhost:3000/apps/5264/production/audit-log?from=2022-12-20T15%3A10%3A37.000Z&eventId=g%3A6617872)- [Axe issue](https://axe.deque.com/issues/e7b864ab-3f43-4222-bf8c-6458308c759d)
> 
> <img alt="Screen Shot 2022-12-22 at 5 58 57 PM" width="549" src="https://user-images.githubusercontent.com/29221840/209255826-db2875fb-acf3-44c6-8194-fe3720cb0bab.png">
> 
> 7. Usage - Axe issues [1](https://axe.deque.com/issues/537378c3-1dc0-4077-8c49-2cd9081a1ab9), [2](https://axe.deque.com/issues/d1d3057a-568c-471d-8ef3-46300d8f9789), [3](https://axe.deque.com/issues/03c6bb7b-7384-4085-97da-dc3b9e91949f)
> 
> <img alt="Screen Shot 2022-12-22 at 6 06 23 PM copy" width="379" src="https://user-images.githubusercontent.com/29221840/209256766-fc23c467-2b44-49b2-b1e6-0bdf94d412e5.png">

Thank you. These issues you mentioned can all be fixed using the correct colors in the VIP Dashboard pull request.

2022-12-28 14:14 UTC, andrea-sdl approved these changes
✅ ✅ ✅ ✅ ✅

2022-12-28 15:19 UTC, djalmaaraujo commented
Merging, and we will fix the blue color of the Notice once @donaghokeeffe send us an updated version of the Valet Theme

2022-12-28 15:19 UTC, merged