Update RadioBoxGroup component
Automattic/vip-design-system pull request #182
Opened 2023-02-10 14:51 UTC by luiztiago

## Description

Updated RadioBoxGroup component following A11Y recommendations.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/199867/218121669-3e0f489b-d32b-4172-8420-904c7623d1dd.png">

## Checklist

- [ ] This PR has good automated test coverage
- [x] The storybook for the component has been updated

## Steps to Test

1. Pull down PR.
1. `npm run dev`.
1. Open Storybook.
1. Turn on the Voiceover.
1. Test the Radio Button Group component using the keyboard.

2023-02-10 20:09 UTC, djalmaaraujo requested changes
Great work @luiztiago. Thank you! Just one minor thing

2023-02-10 20:09 UTC, djalmaaraujo commented on src/system/Form/RadioBoxGroup.js
> +	option: { id, value, className, label, description, labelProps = {}, ...restOption },
can you change id to `forLabel`? This is what we are using for all inputs and controls.

2023-02-14 01:50 UTC, djalmaaraujo approved these changes

2023-02-14 01:50 UTC, merged

2023-02-20 10:12 UTC, Caitboard commented
This fix is the way it's supposed to be done! I have one hiccup, though. There is a bug in VoiceOver, which causes issues with `<span>`s inside `<label>`s. Currently the selected radiobutton is announced as "Oneand one more item and one more item". 
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/17273342/220075632-f9691cc7-dcda-4c50-a903-eb0b561ed815.png">
Please see [Article about VoiceOver issue with` <span>`s in `<label>`s](https://scholar.harvard.edu/ccwilcox/blog/safari-voiceover-problem-reading-input-labels).
The description is currently inside a span with `display:block`. If I change that to `inline`, VoiceOver does announce it as it should. However this would mess up your styling. 

You could either:
- Find a way to work around this in the styling
- Use `aria-describedby` instead. So we would have a label of "One" and the input field would have an `aria-describedby` that refers to the element that contains the description.