Add hint option to Checkbox input
Automattic/vip-design-system pull request #377
Opened 2024-04-23 18:52 UTC by kat3samsin

## Description

A few sentences describing the overall goals of the pull request. Any special considerations and decisions.

Also include any references to relevant discussions and documentation.

## Checklist

- [x] This PR has good automated test coverage
- [x] The storybook for the component has been updated

## Steps to Test

Outline the steps to test and verify the PR here.

Example:

1. Pull down PR.
1. `npm run dev`.
1. Open Storybook.
1. Eat cookies.
1. Verify cookies are delicious.

2024-04-23 21:43 UTC, djalmaaraujo requested changes
@kat3samsin I believe this PR is doing way more than just adding the hint to checkboxes. This changes the way the checkbox is made.

It does not feel "right" the Checkbox should handle this, but a component more like "FormField" that would use checkbox/radio/input, add a label, validation, etc.

Doing the way this PR is implemented we would have code duplication with other components.

Should we discuss more in depth?

2024-04-23 21:43 UTC, djalmaaraujo commented on src/system/Form/Checkbox/Checkbox.tsx
> +						</StyledCheckbox>
This whole block is repeated below.

2024-04-23 21:43 UTC, djalmaaraujo commented on src/system/Form/Checkbox/Checkbox.tsx
> +				</StyledCheckbox>
Repeat

2024-04-23 21:43 UTC, djalmaaraujo commented on src/system/Form/Checkbox/Checkbox.tsx
> +					<Validation isValid={ false } describedId={ forLabel }>
isValid is always false?

2024-04-23 21:59 UTC, djalmaaraujo commented
@kat3samsin This "works", might just need CSS, can you check?

```
<Form.Input
			forLabel="input-with-error"
			label="Error Checkbox"
			errorMessage="Please type numeric characters only"
			as={ () => (
				<Checkbox onCheckedChange={ () => {} } checked aria-labelledby="input-with-error-var" />
			) }
			hasError
		/>
```

2024-04-24 14:58 UTC, kat3samsin commented
>```
<Form.Input
			forLabel="input-with-error"
			label="Error Checkbox"
			errorMessage="Please type numeric characters only"
			as={ () => (
				<Checkbox onCheckedChange={ () => {} } checked aria-labelledby="input-with-error-var" />
			) }
			hasError
		/>
```

Thanks for this suggestion I'll try it this way first.

2024-04-24 20:44 UTC, kat3samsin commented
Closing this PR, I'll just go with adding <Validation> component in the UI.

2024-04-24 20:44 UTC, closed without merging